import { Customer } from "@/models/Customer";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Awesome App: Customers",
    description: "Generated by create next app",
    keywords: ["global customers", "tech companies", "fortune 500"]
};

export default async function Customers() {

    //api call/database call
    const url = `${process.env.BASE_URL}/customers`;
    const res = await fetch(url, { method: "GET" });
    const customers = await res.json() as Customer[];
    return (<div>
        <h6>Customers</h6>
        <table className="table">
            <thead>
                <tr>
                    <th>Customer ID</th>
                    <th>Name</th>
                    <th>Location</th>
                </tr>
            </thead>
            <tbody>
                {customers.map(customer => (
                    <tr key={customer.id}>
                        <td>{customer.id}</td>
                        <td><Link href={"/customers/"+customer.id}>{customer.name}</Link></td>
                        <td>{customer.location}</td>
                    </tr>
                ))}
            </tbody>
        </table>
    </div>)
}