import type { Metadata } from "next";
import "./globals.css";
import AppBar from "@/components/AppBar";
import ReduxProvider from "@/redux/ReduxProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en">
      <body>
        <ReduxProvider>
          <div className="container">
            <AppBar />
            <main>
              {children}
            </main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
