import type { Metadata } from "next";
import "./globals.css";
import AppBar from "@/components/AppBar";
import ReduxProvider from "@/redux/ReduxProvider";
import { AppThemeContext, AppThemeContextProvider } from "@/context/AppThemeContext";


export const metadata: Metadata = {
  title: "Awesome App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en">
      <body>
        <ReduxProvider>
          <AppThemeContextProvider>
            <div className="container">
              <AppBar />
              <main>
                {children}
              </main>
            </div>
          </AppThemeContextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
